worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # DIRETIVA CRÍTICA: Localização do ficheiro com a pass "1234"
    ssl_password_file  ssl/global.pass;

    server {
        listen       443 ssl;
        server_name  app.cyber.local localhost;

        # Caminhos dos certificados gerados pelo seu script
        # Certifique-se de que os ficheiros estão na pasta conf/ssl/
        ssl_certificate      ssl/fullchain.crt;
        ssl_certificate_key  ssl/server.key;

        # Configurações de Segurança do Projeto
        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        # Implementação de HSTS
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}